### ISSUE TITLE
Display Previous Report in Official Report Interface

### ISSUE THREAD

**Issue by benmuirhead** [Bernie-2016/votetracker#19]
When going to submit a county or precinct level report, display next to each county or precinct the last report submitted for that county/precinct. This will allow vols to see which precincts are still needed, if a county has additional data to report, or if a vol needs to correct a report.

**Comment by lady3bean** [comment]
We think that this risks confusing users, adding in past data along with new data if somebody doesn't clear the form, and forcing users to clear the fields if they need to type in new data.
