### ISSUE TITLE
Votetracker or VoteTracker or Vote Tracker?

### ISSUE THREAD

**Issue by net** [Bernie-2016/votetracker#25]
There's a lack of constancy across the project.

**Comment by lady3bean** [comment]
We should go for VoteTracker, so we can change that wherever we notice.

**Comment by kav** [comment]
Ah, damn was just changing it to Vote Tracker in #28

**Comment by lady3bean** [comment]
haha, just saw that!

**Comment by kav** [comment]
VoteTracker it is
