### ISSUE TITLE
Some Precinct Names are wrapped in quotes

### ISSUE THREAD

**Issue by benmuirhead** [Bernie-2016/votetracker#35]
See here for example:
https://votetracker.berniesanders.com/report/AR/ASHLEY/
Probably can be fixed by just stripping out any double quotes, or removing them from the end and beginning of precinct name
![image](https://cloud.githubusercontent.com/assets/3359970/13419339/242de4da-df4b-11e5-8678-9022596b0a7b.png)

**Comment by benmuirhead** [comment]
Note that this is also throwing all of the precinct names out of order because " comes before any letters

**Comment by gnarf** [comment]
We could sanitize this in the fixtures.

**Comment by gnarf** [comment]
Looking at the newest fixture import -- I don't see these quotes anymore.  I think we are okay?
