### ISSUE TITLE
Fixing FAQ page text format

### ISSUE THREAD

**Issue by benmuirhead** [Bernie-2016/votetracker#36]
Can we format the text on https://votetracker.berniesanders.com/faq into bullet point format, or more clearly show the questions vs answers?

![image](https://cloud.githubusercontent.com/assets/3359970/13419658/e5f88672-df4d-11e5-8eb0-83526ab1aa1a.png)

**Comment by gnarf** [comment]
<img width="941" alt="screenshot 2016-03-01 05 29 52" src="https://cloud.githubusercontent.com/assets/549355/13424416/addf38f0-df6e-11e5-91f8-2f5ec4ae8f67.png">

**Comment by gnarf** [comment]
7a39d8e
