### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [Bernie-2016/votetracker#48]
in this code:

``` js
  db.query('SELECT * FROM pg_stat_activity', true).then(result => {
    res.send(result);
  });
```
- if a query like this fails, it will throw an error because you do not provide a `.catch` handler.
- passing `true` as parameter in this query does precisely nothing, as the query has no variables in it.

**Comment by tkellen** [comment]
Thanks @vitaly-t! This code will be removed, it was just put there as a bare-bone example of something working.
