### ISSUE TITLE
client side form validation

### ISSUE THREAD

**Issue by lady3bean** [Bernie-2016/votetracker#9]

**Comment by jennschiffer** [comment]
i can take this on if no one else has :santa:

**Comment by jennschiffer** [comment]
are there any weird requirements besides required fields and checking for valid input types?

**Comment by gnarf** [comment]
yeah - basically "you added some values to these forms"

Some notes:   I would like to ensure that at least one of the numbers is >0 in the "caucus" form and the "official" form (if one is >0, others can be empty and default to 0), also no negative numbers.
